prepare next version for ubuntu 0.7.24

diff --git a/debian/apt-cacher-ng.postinst b/debian/apt-cacher-ng.postinst
--- a/debian/apt-cacher-ng.postinst
+++ b/debian/apt-cacher-ng.postinst
@@ -3,7 +3,7 @@
 . /usr/share/debconf/confmodule
 
 NAME=apt-cacher-ng
-CDIR=/var/cache/$NAME
+CONFIGFILE=/etc/$NAME/zz_debconf.conf
 LDIR=/var/log/$NAME 
 SLIST=/etc/apt/sources.list
 CFG=/etc/apt-cacher-ng
@@ -11,6 +11,7 @@ DDIR=/usr/lib/apt-cacher-ng
 VDIR=/var/lib/apt-cacher-ng
 udefault=$VDIR/backends_ubuntu.default
 ddefault=$VDIR/backends_debian.default
+BINPATH=/usr/sbin/$NAME
 
 gen_mirror_list_from_sources_list() {
 
@@ -82,13 +83,21 @@ guess_ubuntu_mirrors() {
    
    tmpfile="`mktemp`"
 
+   if [ ! "$http_proxy" ] ; then
+      prx=$(apt-config dump | grep Acquire::http::Proxy | cut -f2 -d'"') || true
+      if [ "$prx" ] ; then
+         http_proxy="$prx"
+         export http_proxy
+      fi
+   fi
+
    # may hit a local mirror which also hosts Debian, use it then
    sed -e 's,\([a-z]\)/.*,\1,' < $CFG/backends_debian | xargs -n1 -i grep "{}" $DDIR/ubuntu_mirrors > $tmpfile || true
 
    # mirror suggestions from Ubuntu's service might be a good candidate
    if ! test -s $tmpfile ; then
       mirurl=http://mirrors.ubuntu.com/mirrors.txt
-      wget -q -O- $mirurl >> $tmpfile 2>/dev/null || curl -s $mirurl >> $tmpfile 2>/dev/null || true
+      wget -q -O- $mirurl >> $tmpfile 2>/dev/null || curl -s $mirurl >> $tmpfile 2>/dev/null || BECURL=$mirurl $BINPATH >> $tmpfile 2>/dev/null || true
    fi
 
    # still nothing. Sneak more information from Debian backend configuration?
@@ -124,14 +133,53 @@ gen_lists() {
 
 if [ "$1" = "configure" ]; then
 
-   # user should exist. adduser sometimes fails (system range issue) but that's ok
-   adduser --quiet --system --group --no-create-home --home $CDIR $NAME || id $NAME
+   db_get $NAME/cachedir
+   case "$RET" in
+      keep|"")
+         # not to be set by debconf mechanism, use whatever we have
+         CDIR=$(PRINTCFGVAR=CacheDir $BINPATH -c $CFG 2>/dev/null)
+         CDIRCONF="# not set by debconf"
+         ;;
+      *)
+         # ok, configured by debconf
+         CDIR="$RET"
+         CDIRCONF="CacheDir: $RET"
+         ;;
+   esac
 
-   for x in $CDIR $LDIR ; do 
+   # make sure it's set even if commented out by the user
+   TESTPATH=$(PRINTCFGVAR=CacheDir $BINPATH -c $CFG 2>/dev/null)
+   if test -e "$TESTPATH" ; then
+      CDIR=/var/cache/$NAME
+      CDIRCONF="CacheDir: $CDIR"
+   fi
+
+   # user should exist. adduser sometimes fails (system range issue) but that's ok
+   adduser --quiet --system --group --no-create-home --home "$CDIR" $NAME || id $NAME
+   # also setup permissions ASAP
+   if [ -z "$(dpkg-statoverride --list $CFG/security.conf)" ] ; then
+      dpkg-statoverride --update --add apt-cacher-ng apt-cacher-ng 600 $CFG/security.conf
+   fi
+
+   # be sure about that even if the user messed it up
+   for x in "$CDIR" $LDIR ; do 
       if [ ! -d "$x" ]; then
          install -d -g $NAME -o $NAME -m2755 "$x"
       fi
    done
+
+   # creating some stubs
+   # least invasive cooperation with the old style behavior for now
+   for cfn in backends_debvol backends_ubuntu backends_debian ; do
+      if ! test -e $CFG/$cfn ; then
+         if test -e $CFG/oldconffiles/$cfn ; then
+            mv -f $CFG/oldconffiles/$cfn $CFG/$cfn
+         else
+            install -m644 /dev/null $CFG/$cfn
+         fi
+      fi
+   done
+   rm -rf $CFG/oldconffiles
 
    db_get apt-cacher-ng/gentargetmode || true
 
@@ -149,13 +197,66 @@ if [ "$1" = "configure" ]; then
       ;;
    esac
 
+   db_get $NAME/bindaddress
+   BINDADDRESS="$RET"
+   if [ x"$BINDADDRESS" = x"all" ] ; then
+      BINDADDRESS='BindAddress: '
+   elif [ x"$BINDADDRESS" = x"keep" ] ; then
+      BINDADDRESS='# BindAddress is set by other config file(s)'
+   else
+      BINDADDRESS="BindAddress: $BINDADDRESS"
+   fi
+
+   db_get $NAME/port
+   PORT="$RET"
+   if [ x"$PORT" = x"keep" ] || [ x"$PORT" = x ] ; then
+      PORT='# Port is set by other config file(s)'
+   else
+      PORT="Port: $PORT"
+   fi
+
+   db_get $NAME/proxy
+   PROXY="$RET"
+   if [ x"$PROXY" = x ] ; then
+      PROXY='Proxy:'
+   elif [ x"$PROXY" = x"keep" ] ; then
+      PROXY='# Proxy set by other config files(s)'
+   else
+      if echo "$PROXY" |grep -q '@' ; then
+         # well, there are credentials which is bad. This better goes into a file with restricted permissions.
+         install -m 600 -o apt-cacher-ng -g apt-cacher-ng /dev/null $CFG/zz_debconf_security.conf
+         cat << HERESEC >$CFG/zz_debconf_security.conf
+# This file is created if the proxy contains user/password data
+# and is removed otherwise.
+Proxy: $PROXY        
+HERESEC
+         PROXY=
+      else
+         PROXY="Proxy: $PROXY"
+         rm -rf $CFG/zz_debconf_security.conf
+      fi
+   fi
+
+   cat << HERE > $CONFIGFILE
+# This is a configuration generated file managed by the package configuration
+# scripts of apt-cacher-ng. All manual changes here will be overriden.
+# To reconfigure particular settings, please run:
+# dpkg-reconfigure apt-cacher-ng -plow
+
+# See acng.conf and apt-cacher-ng documentation for more details.
+# To override this values permanently, put the assignments into a file
+# like /etc/apt-cacher-ng/zzz_override.conf .
+
+$PROXY
+$PORT
+$BINDADDRESS
+$CDIRCONF
+
+HERE
+
    db_stop || true
 
    rm -f $CFG/in.acng $CFG/mount.acng
-
-   if [ -z "$(dpkg-statoverride --list $CFG/security.conf)" ] ; then
-      dpkg-statoverride --update --add apt-cacher-ng apt-cacher-ng 600 $CFG/security.conf
-   fi
 
    set_def_files
 fi
